### ISSUE TITLE
Do not restart processing from scratch all the time

### ISSUE THREAD

**Issue by koobs** [devmount/third-stats#130]
**Is your feature request related to a problem? Please describe.**

At present, ThirdStats starts processing mail from scratch each time:

 * The toolbar menu is opened
 * Each time the account is switched in the dashboard view

Additionally, if existing mail has already been completely processed at least once, the existing stats are cleared/removed

This represents unnecessary:

 * CPU and IO utilisation
 * Wait times for the user before useful information is visible
 * Removal of useful information while background processing can occur instead

The above is particularly degenerate for users with large mailboxes. I do understand that the present behaviour is very likely only due to ThirdStats being new, and it being the simplest option which also doesn't require state.

**Describe the solution you'd like**

* If existing mail has been completely processed at least once, a user can view the existing stats while mail is re-processed or stats are updated
* If existing mail has *not* yet been completely processed at least once, processing is not *reset* each time the menu or dashboard is re-opened, or accounts are switched. This effectively means 'processing continues if it has already started'.

**Describe alternatives you've considered**

See below. Since a specific implementation has not been proposed (just a behaviour change), no specific alternatives have been investigated.

**Additional context**

 * Open question: On what basis (event, period, timer or otherwise) should stats/mail be re-processed (from scratch), or updated
  * This probably shouldn't happen *every* time a new piece of mail is received, moved or deleted. Perhaps folder 'compact' functionality, expunge or similar events could be leveraged. Otherwise some `every <period>` might be suitable, possibly exposed as a user option down the track.
 * Open question: How should one store 'current state' of processing. This may be as simple as a per-account 'lock file' style mechanism, such that only a single 'processing' process may be running per account.
 * Open question: In the event of processing/state bugs, how can a user recover or fix stats. Suggestion: A rebuild/refresh function (I will submit a separte issue for this, for this and other reasons)

**Comment by devmount** [comment]
Thank you @koobs. This will be the major change in the next release v1.0.0 as this is something, that bothered me from the beginning of ThirdStats 😅 and it is exactly as you thought: The current behaviour is simply because it was the easiest to implement in the early states of ThirdStats.

Some technical information:
- Thunderbird offers the same storage API as Firefox, which offers 5MB of extension storage without additional permissions. That is more than enough to store the processed account data. One account takes approx. 70KB of storage, which means up to 70 accounts can be stored (well you never know what people do with your software, but that should be sufficient 😅)
- The process will be the following:
  - Open an account for the first time in ThirdStats (no storage entry yet): Account is being processed with a loading spinner as already known from the current state
  - Open an account again (either from the popup menu or from the account selection in the stats tab or from restarting Thunderbird): Account stats data is loaded from storage and directly served (without a loading spinner).

Some procedure information:
- At first, the only option to rebuild the stored stats data will be a manual refresh button.
- After successfully launching this feature, there will be a configurable background process to do the processing in a time interval, that can be set in the add-on options

How does that sound?

**Comment by koobs** [comment]
@devmount Apologies for the lack of response on this. I'll test the initial implementation when its out and provide feedback. Thank you for taking care of this :)

**Comment by devmount** [comment]
@koobs No problem at all, it would be a great help if you test this and give feedback 👍🏻

**Comment by devmount** [comment]
@koobs This feature is now released. Please test it and issue a bug report, if something doesn't work as expected. Thank you!

**Comment by koobs** [comment]
@devmount Will test tonight and provide feedback for issue resolution/close, thanks again! :)

**Comment by koobs** [comment]
I've tested the new 0.8.0 version, which enables the processing 'cache'. Mentioned in the original feature description, but not present in this version, is:

- Clicking on the toolbar icon starts processing again each time it is opened

ThirdStats should implement a 'lockfile' style mechanism so that processing can continue, and only a single instance of the processing per account can run at any one time.

Additionally (new bug identified)

- While a refresh is running (initiated via the menu icon), then clicking into an account to access the full dashboard view, the refresh is no longer running.

My guess is that there's an event handler for the menu icon that initiates the processing every time the button is clicked, and that the dashboard view (refresh icon) is not aware of the processing state so it doesn't show it.

From here, I would:

- [ ] Add a refresh icon to the menu that can be user initiated (without needing to go to full dashboard)

Modify the toolbar/menu icon on-click/open handler to:

- [ ] IF stats are available (eg: processing has finished at least once[ 1], do nothing
- [ ] ELSE (there are *no* stats for any enabled account): initiate processing

Additional Considerations:

1) When to 'first' initiate processing is an interesting question. It is currently only initiated on menu open and refresh in dashboard.

We may want to remove entirely the "on menu open, initiate processing", in favour of some other 'first run' mechanic, such as a welcome screen. This would reduce the complexity of the menu event handling, leaving only display of current stats, and decouple processing from menu event handlers entirely

1) How to define 'we have stats' or 'processing has already been done'

The original report contained a consideration:

Open question: On what basis (event, period, timer or otherwise) should stats/mail be re-processed (from scratch), or updated

We may want to consider:

1) Using a variable or setting that contains the a date/timestamp of the last completed processing run for an account (the setting should be keyed on the account name). This would allow ThirdStats to implement a 'periodic refresh' functionality based on a timer, that checks the last completed processing stamp and compares the time to now.

**Comment by koobs** [comment]
@devmount If you'd like (since this issue is closed), I can create the remaining issues as separate new issues. Alternatively (if you'd prefer), you can re-open this and I'll create the remaining things as individual checkmarks

**Comment by devmount** [comment]
Thank you Kubilay. I'm currently considering removing the popup menu completely and linking the toolbar icon directly to the stats page. I was never really satisfied with this popup menu as it offers very little added value.

Alternatively I can only remove the messages count from the popup menu. This would remove the processing and waiting times on clicking on the toolbar icon.
What do you think?

**Comment by devmount** [comment]
> Clicking on the toolbar icon starts processing again each time it is opened

> While a refresh is running (initiated via the menu icon), then clicking into an account to access the full dashboard view, the refresh is no longer running.

Yes this is because TB handles popup and stats page as completely separate instances. Implementing additional storage for the popup seems to be a bit too much for just a popup that should just launch the stats page. (That's why my considerations in the last comment). I'd rather like to keep it simple on this point.

> When to 'first' initiate processing

I like the current approach. When opening the stats page and no cache entry exists, process data. If not, retrieve data from Cache. Currently there is only a manual refresh button, but I will implement an option for a time interval in the future.

> Using a variable or setting that contains the a date/timestamp of the last completed processing run for an account

That is a very good idea. This will indicate, how old the currently display data is, which is a UX improvement.

**Comment by koobs** [comment]
> Alternatively I can only remove the messages count from the popup menu. This would remove the processing and waiting times on clicking on the toolbar icon.
> What do you think?

yeh, not a bad idea. perhaps we can resurrect it if we can come up with something compelling for its contents.

Zero thinking ideas:

- sparklines / heatmap of some primary metric, count or stat
- maybe just show the message totals, but not have processing be initiated at all. 

Or does the menu require (force) processing?

**Comment by devmount** [comment]
Unfortunately the message count requires processing. There is (currently) no other way with the web extensions API than to iterate over all messages of all folders.

**Comment by devmount** [comment]
Out of our thoughts, I created the following issues:

- Remove processing from Popup (Toolbar button) #174
- Add primary metrics to Popup (Toolbar button) loaded from cache if cache exists (no processing necessary) #175
- Add timestamp to cache entries and show it everywhere data is shown from cache #176

We can use the [discussions section](https://github.com/devmount/third-stats/discussions) for further brainstorming this topic, as I will close this issue here.
