### ISSUE TITLE
Detailed information on senders/recipients

### ISSUE THREAD

**Issue by rfwolff** [devmount/third-stats#193]
The visual representation of results could be improved if email addresses, listed under "most received from" or "most sent to", respectively, would be clickable to show details for that address. For example, a click on the first entry in "most received from" would visualise (activity over time, daytime, weekday, month, temporal distribution etc.) data for that address.

**Comment by devmount** [comment]
Thank you for this request. So in fact, this would be an additional filter for contact specific stats. Since I'm using Chart,js to generate the charts, I have to see if there's a click listener for single elements in a bar chart. It's definitely possible to implement this as a drop-down, like the folder filter.

**Comment by rfwolff** [comment]
Sounds good, thanks for looking into it.

**Comment by devmount** [comment]
This is now implemented with #262. Please test it and let me know, if there are any issues. Have a nice sunday!
