### ISSUE TITLE
Virtual Folder breaks ThirdStats

### ISSUE THREAD

**Issue by paulmassen** [devmount/third-stats#282]
Hi, 

I'm an user of the thunderbird feature called "Virtual Folder" (aka "search folder), which is created by File->New->Virtual Folder.

Having one of these folders breaks Third Stats (stuck on chart generation, email count = 0 etc.)

Removing the virtual folder will resolve the problem.

Hope it helps, and please let me know would you need any more details.

All best, 

Paul

**Comment by devmount** [comment]
Thank you for reporting this.

Which Thunderbird version do you use on which OS (please always use and fill in the issue template when creating issues 🙏🏻)? I don't have a "Virtual Folder" menu entry, did you mean "Saved Search"?

![image](https://user-images.githubusercontent.com/5441654/112339425-ec895f00-8cbf-11eb-8095-f407c8ffb4b4.png)

It might be related to #19 (in that case it would be fixed with the next major release of Thunderbird).
Can you check, if the solution proposed in https://github.com/devmount/third-stats/issues/239#issuecomment-773606896 eventually solves the problem?

**Comment by paulmassen** [comment]
Sorry for the template, and yes, I meant "search folder" (virtual folder in french !) , after reading more into the other issues, I re-created the folder again, and am now still able to use Third Stats.

While I had this problem, I was able to catch this error in the console, which lead me to think that the search folder could be the problem.

`Uncaught (in promise) Error: Folder not found: /INBOX/Sent/Search folder`

I will try to re-create the issue again, but meanwhile, I guess I can close this issue ?

Here is my Thunderbird version: 78.8.1 on macOS Big Sur 11.1 / Apple M1

**Comment by devmount** [comment]
> I will try to re-create the issue again, but meanwhile, I guess I can close this issue ?

I don't think there is anything more to do on my end, You can close this. The "folder not found" issue is very likely caused by Thunderbird itself, I'm afraid you'll have to wait until the next major release.

**Comment by paulmassen** [comment]
Thanks, yes, I'm closing this and I will let you know if someday the issue re-appear.
